# Generated by Django 4.2.7 on 2023-12-03 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.AutoField(db_column='userID', default=1000000000, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=20, unique=True)),
                ('bio', models.TextField(blank=True, default="Hello! I'm a new Sips user!")),
                ('password', models.CharField(max_length=25)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
                'db_table_comment': 'hosts basic user information',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.IntegerField(db_column='postID', default=3000000000, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.TextField()),
                ('likes', models.IntegerField()),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.IntegerField(db_column='commentID', default=4000000000, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('postid', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='sips_app.post')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followerid', models.ForeignKey(db_column='followerID', on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
                ('hostid', models.ForeignKey(db_column='hostID', on_delete=django.db.models.deletion.CASCADE, related_name='host_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Follow',
                'unique_together': {('hostid', 'followerid')},
            },
        ),
        migrations.CreateModel(
            name='Feedbuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='sips_app.post')),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'FeedBuilder',
                'unique_together': {('userid', 'postid')},
            },
        ),
    ]
