# Generated by Django 4.2.7 on 2023-12-04 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentid',
            field=models.AutoField(db_column='commentID', default=3000000000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postid',
            field=models.AutoField(db_column='postID', default=2000000000, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionid', models.AutoField(db_column='transactionID', default=4000000000, primary_key=True, serialize=False)),
                ('itemid', models.CharField(choices=[('theme_darkmode', 'Dark Mode'), ('theme_highcontrast', 'High Contrast'), ('theme_custom', 'Custom Theme')], max_length=20)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
