# Generated by Django 4.2.7 on 2023-12-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0003_alter_comment_commentid_alter_post_postid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='Transaction',
        ),
    ]
