# Generated by Django 4.2.7 on 2023-12-05 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0004_alter_transaction_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='messageID', default=5000000000, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('recipientid', models.ForeignKey(db_column='recipientID', on_delete=django.db.models.deletion.CASCADE, related_name='recipient_set', to=settings.AUTH_USER_MODEL)),
                ('senderid', models.ForeignKey(db_column='senderID', on_delete=django.db.models.deletion.CASCADE, related_name='sender_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message',
            },
        ),
    ]
