# Generated by Django 4.2.7 on 2023-12-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(choices=[('theme_darkmode', 'Dark Mode'), ('theme_highcontrast', 'High Contrast'), ('theme_custom', 'Custom Theme')], db_column='itemName', max_length=20)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='itemid',
            field=models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, to='sips_app.item'),
        ),
    ]
