# Generated by Django 4.2.7 on 2023-12-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0008_alter_comment_commentid_alter_message_messageid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(db_column='userID', primary_key=True, serialize=False),
        ),
    ]
