# Generated by Django 4.2.7 on 2023-12-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0010_alter_comment_commentid_alter_message_messageid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
