# Generated by Django 4.2.7 on 2023-12-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sips_app', '0013_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
